schema = 3

[mod]
  [mod."github.com/joho/godotenv"]
    version = "v1.5.1"
    hash = "sha256-kA0osKfsc6Kp+nuGTRJyXZZlJt1D/kuEazKMWYCWcQ8="
  [mod."github.com/urfave/negroni"]
    version = "v1.0.0"
    hash = "sha256-l7ExYayxsfYdqYYcYQd5n1AOP/187IIdsizEpsiR5r4="
